In [1]:
using PyCall

const irbasis = pyimport("irbasis")

PyObject <module 'irbasis' from '/home/shinaoka/.local/lib/python3.8/site-packages/irbasis-2.2.3-py3.8.egg/irbasis/__init__.py'>

In [2]:
# Load basis data for fermions and Lambda = 1000.0
basis = irbasis.load("F", 1000.0)

PyObject <irbasis.irbasis.basis object at 0x14d6b80b0220>

In [3]:
# l=0, x = 0.1
basis.ulx(0, 0.1)

0.27401896348952326

In [4]:
# Compute u_l(x) for all l's at 10 x points.
# This can be done by using numpy broadcasting.
function compute_ulx_all_l(basis, xs)
    dim = convert(Int64, basis.dim())
    nx = length(xs)
    all_l = collect(0:dim-1) # make sure l starts with 0.
    basis.ulx(reshape(all_l, dim, 1), reshape(xs, 1, nx))
end
nx = 10
xs = LinRange(-1, 1, nx)
ulx_mat = compute_ulx_all_l(basis, xs)
size(ulx_mat)

(72, 10)

In [5]:
# Compute unl for n=0, ...., 100
unl = basis.compute_unl(collect(0:100))
size(unl)

(101, 72)

In [6]:
# Sampling points in x space
sp_x = basis.sampling_points_x(basis.dim()-1)

72-element Vector{Float64}:
 -0.9999350180790227
 -0.999591919067488
 -0.998810514553798
 -0.9975735342137606
 -0.995868107425596
 -0.993676225696257
 -0.9909740539653258
 -0.9877311295042808
 -0.9839093450370975
 -0.9794616818172159
 -0.9743306649327053
 -0.9684465198121114
 -0.9617250208563004
  ⋮
  0.9684465198121114
  0.9743306649327053
  0.9794616818172162
  0.9839093450370976
  0.9877311295042808
  0.9909740539653258
  0.993676225696257
  0.995868107425596
  0.9975735342137606
  0.998810514553798
  0.999591919067488
  0.9999350180790227

In [7]:
# Dimensionless version of F matrix for sparse sampling
F = transpose(compute_ulx_all_l(basis, sp_x))

72×72 transpose(::Matrix{Float64}) with eltype Float64:
 6.02087  -8.04567   9.48639    -10.5652     …  -5.7562    5.64904  -5.54162
 5.75039  -7.64106   8.79298     -9.58333        5.2586   -5.19723   5.1292
 5.22002  -6.84939   7.44944     -7.6984        -4.14515   4.11459  -4.0676
 4.56897  -5.88165   5.83787     -5.47791        3.48043  -3.47632   3.44334
 3.92892  -4.93653   4.31109     -3.43615       -3.03602   3.05866  -3.03749
 3.3726   -4.12265   3.05309     -1.82861    …   2.70883  -2.76005   2.75014
 2.91728  -3.46444   2.09371     -0.6797        -2.45021   2.53266  -2.53418
 2.55077  -2.94191   1.38475      0.0983916      2.23412  -2.35096   2.36455
 2.2534   -2.52421   0.862301     0.61095       -2.04508   2.19992  -2.22653
 2.00797  -2.18467   0.473613     0.94159        1.8731   -2.06984   2.11067
 1.80177  -1.90373   0.181174     1.14795    …  -1.71132   1.95407  -2.01054
 1.62576  -1.66755  -0.0407086    1.26829        1.55485  -1.84777   1.92144
 1.47345  -1.46629  -0

In [8]:
# Sampling points in n
sp_n = basis.sampling_points_matsubara(basis.dim()-1)

72-element Vector{Int64}:
 -1739
  -716
  -435
  -307
  -234
  -186
  -151
  -126
  -106
   -90
   -77
   -66
   -57
     ⋮
    65
    76
    89
   105
   125
   150
   185
   233
   306
   434
   715
  1738

In [9]:
# Dimensionless version of hatF matrix for sparse sampling
hatF = basis.compute_unl(sp_n)

72×72 Matrix{ComplexF64}:
 -0.0-0.00157101im   -5.95226e-5+0.0im  …  -0.00322053+0.0im
 -0.0-0.00379364im  -0.000345927+0.0im      0.00849325+0.0im
 -0.0-0.00617193im  -0.000909578+0.0im       -0.013881+0.0im
 -0.0-0.00859539im   -0.00174668+0.0im       0.0191966+0.0im
 -0.0-0.0110285im    -0.00283801+0.0im      -0.0243999+0.0im
 -0.0-0.0135049im    -0.00418642+0.0im  …    0.0294781+0.0im
 -0.0-0.0161079im    -0.00583646+0.0im      -0.0344425+0.0im
 -0.0-0.0186518im    -0.00765254+0.0im       0.0394045+0.0im
 -0.0-0.0213354im    -0.00975744+0.0im      -0.0443181+0.0im
 -0.0-0.0241132im     -0.0121115+0.0im       0.0492602+0.0im
 -0.0-0.0269863im     -0.0147053+0.0im  …   -0.0542247+0.0im
 -0.0-0.0300525im      -0.017624+0.0im       0.0595113+0.0im
 -0.0-0.033191im      -0.0207469+0.0im      -0.0647406+0.0im
     ⋮                                  ⋱  
  0.0+0.0300525im      -0.017624+0.0im  …    0.0595113+0.0im
  0.0+0.0269863im     -0.0147053+0.0im      -0.0542247+0.0im
  0.0+0.0241132